### List books
GET http://localhost:8080/books
Accept: application/json

### Create Book
POST  http://localhost:8080/books
Content-Type: application/json

{
  "ID": 1,
  "Title": "The Great Gatsby",
  "Author": "F. Scott Fitzgerald",
  "Genre": "Fiction"
}

### Get by id books
GET http://localhost:8080/books/1
Accept: application/json

### Update Book
PUT  http://localhost:8080/books/1
Content-Type: application/json

{
  "ID": 1,
  "Title": "The Great Gatsby 3",
  "Author": "F. Scott Fitzgerald 2",
  "Genre": "Fiction"
}


### Delete book
DELETE http://localhost:8080/books/5
Accept: application/json
